name: payments-platform-ci-cd

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ feature/*,hotfix/* ]
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install fastapi uvicorn pydantic requests prometheus-fastapi-instrumentator pytest pytest-cov httpx

      - name: "Run Unit Tests (DORA: Quality Check)" 
        env:        
          PYTHONPATH: ${{ github.workspace }}
        run: |
          pytest -vv -s --durations=5 tests/

      - name: Build Docker Image        
        run: |
          docker build -t payments-api -f docker/Dockerfile .

      - name: Verify Container Startup (Smoke Test)        
        run: |
          docker run -d -p 8000:8000 --name test-container payments-api
          sleep 5
          docker ps | grep test-container
          docker stop test-container



  deploy-local-kind:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create kind Cluster
        uses: helm/kind-action@v1.8.0
        with:
          cluster_name: kind

      - name: Build and Load Image
        run: |
          docker build -t payments-api:local -f docker/Dockerfile .
          kind get clusters
          kind load docker-image payments-api:local --name kind


      - name: Deploy to Kubernetes (kind)
        run: |
          export IMAGE_TAG=payments-api:local
          sed -i "s/\$IMAGE/$IMAGE_TAG/g" k8s/deployment.yaml
          cat k8s/deployment.yaml
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml

      - name: "Wait for Deployment (DORA: Reliability)"
        run: |
          sleep 20
          kubectl get pods
          kubectl describe deployment payments-api
          kubectl rollout status deployment/payments-api --timeout=180s || (kubectl logs -l app=payments-api && exit 1)

      - name: Automated Deployment Tests (15% Criteria)
        run: |        
          echo "Creando túnel hacia el servicio..."
          
          # CORRECCIÓN: local:service_port -> 8000:80
          kubectl port-forward svc/payments-api-service 8000:80 & 
          
          # Damos un poco más de tiempo por si el runner está lento
          sleep 10 
          
          echo "Enviando transacción de prueba a http://localhost:8000/transfer"
          
          # Probamos contra el localhost:8000 del runner
          RESPONSE=$(curl -s -X POST "http://localhost:8000/transfer" \
            -H "Content-Type: application/json" \
            -d '{"amount": 100, "vendor": "vendorA", "txhash": "0x123abc"}')
          
          echo "Respuesta: $RESPONSE"
          
          if echo "$RESPONSE" | grep -q "success"; then
            echo "✅ TEST EXITOSO"
          else
            echo "❌ TEST FALLIDO: Revisa los logs"
            exit 1
          fi

      - name: "DORA & Observability: Traffic Simulation & Metrics"
        if: always()
        run: |
          echo "Simulando tráfico para generar métricas..."
          
       
          # 2. Bucle de peticiones (Simulación de carga)
          # Enviamos 5 peticiones a VendorA, 5 a VendorB y 2 a un Vendor desconocido
          for i in {1..35}; do
            curl -s -X POST "http://localhost:8000/transfer" -H "Content-Type: application/json" \
              -d "{\"amount\": $i$i.50, \"vendor\": \"vendorA\", \"txhash\": \"0x00A$i\"}" > /dev/null
            curl -s -X POST "http://localhost:8000/transfer" -H "Content-Type: application/json" \
              -d "{\"amount\": $i$i.00, \"vendor\": \"vendorB\", \"txhash\": \"0x00B$i\"}" > /dev/null
          done
          
          for i in {1..6}; do
            curl -s -X POST "http://localhost:8000/transfer" -H "Content-Type: application/json" \
              -d "{\"amount\": 10.00, \"vendor\": \"unknown_test\", \"txhash\": \"0xERR$i\"}" > /dev/null
          done

          echo "Peticiones completadas. Extrayendo reporte..."
          echo "===================================================="
          echo "   REPORT DE MÉTRICAS (PROMETHEUS/FASTAPI)          "
          echo "===================================================="
          
          METRICS=$(curl -s http://localhost:8000/metrics)
          
          echo "--- Rendimiento de Tráfico ---"
          echo "$METRICS" | grep "^http_requests_total" || echo "http_requests_total: 0"
          
          echo ""
          echo "--- DORA: Reliability (Transferencias) ---"
          # Filtramos por nombre de métrica específico 
          echo "$METRICS" | grep "^transfer_success_total" || echo "transfer_success_total: 0"
          echo "$METRICS" | grep "^transfer_fail_total" || echo "transfer_fail_total: 0"
          
          echo ""
          echo "--- Latencia ---"
          echo "$METRICS" | grep "^transfer_latency_seconds_sum" || echo "transfer_latency_seconds: N/A"
          echo "===================================================="


  # push-to-ecr:
  #   needs: build-and-test
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout Code
  #       uses: actions/checkout@v4 

  #     - name: Configure AWS credentials
  #       uses: aws-actions/configure-aws-credentials@v4
  #       with:
  #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #         aws-region: ${{ secrets.AWS_REGION }}

  #     - name: Login to Amazon ECR
  #       id: login-ecr
  #       uses: aws-actions/amazon-ecr-login@v2

  #     - name: Build, tag, and push image to Amazon ECR
  #       env:
  #         ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
  #         ECR_REPOSITORY: payments-api
  #         IMAGE_TAG: ${{ github.sha }}
  #       run: |
  #         docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f docker/Dockerfile . 
  #         docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

  # deploy:
  #   needs: push-to-ecr
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout Code
  #       uses: actions/checkout@v4

  #     - name: Configure AWS credentials
  #       uses: aws-actions/configure-aws-credentials@v4
  #       with:
  #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #         aws-region: ${{ secrets.AWS_REGION }}


  #     - name: Terraform Init & Apply
  #       run: |
  #         cd infra/terraform 
  #         terraform init 
  #         terraform apply -auto-approve

  #     - name: Update Kubeconfig
  #       run: aws eks update-kubeconfig --name payments-cluster --region ${{ secrets.AWS_REGION }}

  #     - name: Deploy to EKS
  #       run: |
  #         export IMAGE=$ECR_REGISTRY/payments-api:${{ github.sha }}
  #         envsubst < k8s/deployment.yaml | kubectl apply -f -
  #         kubectl apply -f k8s/service.yaml